
#_meta.script_name: init-db
#
#_base: [local]
##_base: [vault]

########################################################################

#_meta.script_name: parse-csv
#
#overwrite: yes
#
##parser._type: parser/usbank
##path: extra/Credit Card - 3312_01-30-2020_10-03-2023.csv
#
#parser._type: parser/costco
#path: extra/Date range.CSV


########################################################################

#_meta.script_name: usbank-locs
#
#path: extra/usbank-test.json
#loc-path: extra/usbank-sols.csv

_meta.script_name: costco-locs

path: extra/Date range.json
loc-path: extra/Data range-sols.csv

#overwrite: yes

########################################################################


