
#_meta.script_name: init-db
##
###_base: [local]
#_base: [vault]

#db: db/vault/demo.db
#db: novo/report.db

########################################################################

#_meta.script_name: parse-csv
#
#overwrite: yes
#
##parser._type: parser/usbank
##path: extra/Credit Card - 3312_01-30-2020_10-03-2023.csv
#
##parser._type: parser/costco
##path: extra/Date range.CSV
#
#parser._type: parser/amazon
#path: extra/amazon/Chase8182_Activity20211006_20231006_20231006.CSV
#out: extra/amazon/amazon.json

########################################################################

#_meta.script_name: usbank-locs
#
#path: extra/usbank-test.json
#loc-path: extra/usbank-sols.csv


#_meta.script_name: costco-locs
#
#path: extra/Date range.json
#loc-path: extra/Data range-sols.csv

#overwrite: yes

########################################################################

#_meta.script_name: txns
#
#shortcut-path: db/vault/shortcuts.yml
#
##path: extra/usbank/flexperks.json
##account: flex-perks
#
##path: extra/usbank/cashplus.json
#path: novo/cashplus.json
#account: cashplus
#
#report: test
#
#processor._type: processor/usbank
#
#dry-run: yes

########################################################################

#_meta.script_name: init-db

conn._type: sqlite
db: db/novo.db

init-assets: db/vault/assets.yml
init-accounts: db/vault/accounts.yml
init-tags: db/vault/tags.yml

shortcut-path: db/vault/shortcuts.yml

########################################################################

#_meta.script_name: txn

#y: yes

########################################################################

_base: [year2023]

#_meta.script_name: multi-txn

#_meta.script_name: full-reset
_meta.script_name: verify

#parser._type: paypal
#account: paypal
#path: extra/2023/paypal.CSV



